package source.auth.application.service.passkey;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;
import source.auth.application.service.cache.contracts.RedisServicer;

import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.SecureRandom;
import java.security.Signature;
import java.security.KeyFactory;
import java.security.PublicKey;
import java.security.spec.X509EncodedKeySpec;
import java.util.Base64;
import java.util.Map;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.dataformat.cbor.CBORFactory;
import com.fasterxml.jackson.core.type.TypeReference;

@Service
public class PasskeyService {

    private static final Logger log = LoggerFactory.getLogger(PasskeyService.class);
    private final RedisServicer redisService;
    private final SecureRandom secureRandom = new SecureRandom();
    private static final String CHALLENGE_PREFIX = "passkey_challenge:";

    private final ObjectMapper jsonMapper = new ObjectMapper();
    private final ObjectMapper cborMapper = new ObjectMapper(new CBORFactory());

    public PasskeyService(RedisServicer redisService) {
        this.redisService = redisService;
    }

    public String generateChallenge(String username) {
        byte[] challenge = new byte[32];
        secureRandom.nextBytes(challenge);
        String challengeHex = bytesToHex(challenge);

        redisService.setValue(CHALLENGE_PREFIX + username, challengeHex, 60);
        return challengeHex;
    }

    public String consumeChallengeFromRedis(String username) {
        return redisService.getAndDeleteValue(CHALLENGE_PREFIX + username);
    }

    /**
     * Verifies the WebAuthn signature manually.
     * @param username The username.
     * @param expectedChallengeHex The challenge generated by the server.
     * @param signatureB64Url Base64URL encoded signature.
     * @param publicKeyBytes The public key in COSE/CBOR format.
     * @param authDataB64Url Base64URL encoded authenticatorData.
     * @param clientDataJsonB64Url Base64URL encoded clientDataJSON.
     */
    public boolean verifySignature(String username, String expectedChallengeHex, String signatureB64Url, byte[] publicKeyBytes,
                                   String authDataB64Url, String clientDataJsonB64Url) {
        try {
            if (expectedChallengeHex == null) {
                log.warn("Challenge is null for user: {}", username);
                return false;
            }

            // O WebAuthn usa Base64URL (sem padding na maioria das vezes)
            Base64.Decoder b64UrlDecoder = Base64.getUrlDecoder();

            byte[] signatureBytes = b64UrlDecoder.decode(signatureB64Url);
            byte[] authDataBytes = b64UrlDecoder.decode(authDataB64Url);
            byte[] clientDataBytes = b64UrlDecoder.decode(clientDataJsonB64Url);

            // 1. Structural JSON Validation: Challenge, Origin, and Type
            JsonNode clientDataNode = jsonMapper.readTree(clientDataBytes);
            String challengeInClientData = clientDataNode.get("challenge").asText();
            String typeInClientData = clientDataNode.get("type").asText();

            byte[] expectedChallengeBytes = hexToBytes(expectedChallengeHex);
            String expectedChallengeB64Url = Base64.getUrlEncoder().withoutPadding().encodeToString(expectedChallengeBytes);

            if (!expectedChallengeB64Url.equals(challengeInClientData)) {
                log.error("Possible Replay Attack! Challenge mismatch. Expected: {}, Got: {}", expectedChallengeB64Url, challengeInClientData);
                return false;
            }

            if (!"webauthn.get".equals(typeInClientData) && !"webauthn.create".equals(typeInClientData)) {
                log.error("Invalid WebAuthn operation type: {}", typeInClientData);
                return false;
            }

            // 2. Hash do clientDataJSON (SHA-256)
            MessageDigest digest = MessageDigest.getInstance("SHA-256");
            byte[] clientDataHash = digest.digest(clientDataBytes);

            // 3. Concatenação: authenticatorData + SHA256(clientDataJSON)
            byte[] signedData = new byte[authDataBytes.length + clientDataHash.length];
            System.arraycopy(authDataBytes, 0, signedData, 0, authDataBytes.length);
            System.arraycopy(clientDataHash, 0, signedData, authDataBytes.length, clientDataHash.length);

            // 4. Configurar a chave pública Ed25519 (Extraída do mapa COSE/CBOR)
            Signature ed25519 = Signature.getInstance("EdDSA"); // Java 15+ supports EdDSA/Ed25519
            PublicKey publicKey;
            try {
                // If the frontend sends the raw key (32 bytes), wrap it.
                publicKey = loadRawEd25519PublicKey(publicKeyBytes);
            } catch (Exception e) {
                // Try parsing as COSE/CBOR
                try {
                    byte[] rawPublicKey = extractRawKeyFromCOSE(publicKeyBytes);
                    publicKey = loadRawEd25519PublicKey(rawPublicKey);
                } catch (Exception e2) {
                    log.error("Failed to parse public key as raw or COSE/CBOR: {}", e2.getMessage());
                    return false;
                }
            }

            // 5. Verificar a assinatura contra os dados concatenados
            ed25519.initVerify(publicKey);
            ed25519.update(signedData);

            boolean verified = ed25519.verify(signatureBytes);
            log.info("Signature verification result for {}: {}", username, verified);

            return verified;

        } catch (Exception e) {
            log.error("Passkey signature verification failed for user {}: {}", username, e.getMessage());
            return false;
        }
    }

    private java.security.PublicKey loadRawEd25519PublicKey(byte[] rawKey) throws Exception {
        if (rawKey.length != 32) {
            throw new IllegalArgumentException("Ed25519 public key must be exactly 32 bytes.");
        }
        byte[] x509Prefix = new byte[] {
                0x30, 0x2a, 0x30, 0x05, 0x06, 0x03, 0x2b, 0x65, 0x70, 0x03, 0x21, 0x00
        };
        byte[] x509Key = new byte[x509Prefix.length + rawKey.length];
        System.arraycopy(x509Prefix, 0, x509Key, 0, x509Prefix.length);
        System.arraycopy(rawKey, 0, x509Key, x509Prefix.length, rawKey.length);

        java.security.KeyFactory kf = java.security.KeyFactory.getInstance("EdDSA");
        return kf.generatePublic(new java.security.spec.X509EncodedKeySpec(x509Key));
    }

    private byte[] extractRawKeyFromCOSE(byte[] coseCbor) throws Exception {
        Map<Integer, Object> coseMap = cborMapper.readValue(coseCbor, new TypeReference<Map<Integer, Object>>() {});

        // 1: kty (1 = OKP - Octet Key Pair)
        if (!Integer.valueOf(1).equals(coseMap.get(1))) {
            throw new IllegalArgumentException("Invalid COSE Key Type (kty). Expected OKP (1).");
        }

        // 3: alg (-8 = EdDSA)
        if (!Integer.valueOf(-8).equals(coseMap.get(3))) {
            throw new IllegalArgumentException("Invalid COSE Algorithm (alg). Expected EdDSA (-8).");
        }

        // -1: crv (6 = Ed25519)
        if (!Integer.valueOf(6).equals(coseMap.get(-1))) {
            throw new IllegalArgumentException("Invalid COSE Curve (crv). Expected Ed25519 (6).");
        }

        // -2: x (The 32-byte public key)
        Object xObj = coseMap.get(-2);
        byte[] rawKey;
        if (xObj instanceof byte[]) {
            rawKey = (byte[]) xObj;
        } else if (xObj instanceof String) {
            rawKey = Base64.getUrlDecoder().decode((String) xObj);
        } else {
            throw new IllegalArgumentException("Could not find raw public key (x) in COSE map");
        }

        if (rawKey.length != 32) {
            throw new IllegalArgumentException("Ed25519 public key (x) must be exactly 32 bytes.");
        }

        return rawKey;
    }

    private String bytesToHex(byte[] bytes) {
        StringBuilder sb = new StringBuilder();
        for (byte b : bytes) {
            sb.append(String.format("%02x", b));
        }
        return sb.toString();
    }

    private byte[] hexToBytes(String hex) {
        int len = hex.length();
        byte[] data = new byte[len / 2];
        for (int i = 0; i < len; i += 2) {
            data[i / 2] = (byte) ((Character.digit(hex.charAt(i), 16) << 4)
                    + Character.digit(hex.charAt(i + 1), 16));
        }
        return data;
    }
}
