{
  "format_version": 1,
  "sksl": {
    "entrypoint": "bitcoin_hodl_fragment_main",
    "shader": "// This SkSL shader is autogenerated by spirv-cross.\n\nfloat4 flutter_FragCoord;\n\nuniform vec2 iResolution;\nuniform float iTime;\nuniform float uVisualState;\n\nvec4 fragColor;\n\nvec2 FLT_flutter_local_FlutterFragCoord()\n{\n    return flutter_FragCoord.xy;\n}\n\nvoid FLT_main()\n{\n    vec2 fragCoord = FLT_flutter_local_FlutterFragCoord();\n    vec2 p = ((fragCoord * 2.0) - iResolution) / vec2(min(iResolution.x, iResolution.y));\n    vec2 sp = p * 3.0;\n    vec4 symbol_col = vec4(0.0);\n    float f = 0.0;\n    for (float i = 1.0; i <= 8.0; i += 1.0)\n    {\n        float s = sin((0.699999988079071044921875 * iTime) + ((i * 0.5) * iTime)) * 0.20000000298023223876953125;\n        float c = cos((0.20000000298023223876953125 * iTime) + ((i * 0.5) * iTime)) * 0.20000000298023223876953125;\n        f += (0.00999999977648258209228515625 / abs(length((p * 0.75) + vec2(c, s))));\n    }\n    vec3 bootColor = vec3(0.180000007152557373046875, 0.4600000083446502685546875, 1.0);\n    vec3 warningColor = vec3(1.0, 0.07999999821186065673828125, 0.180000007152557373046875);\n    vec3 retryColor = vec3(1.0, 0.7799999713897705078125, 0.119999997317790985107421875);\n    vec3 currentLightsColor = bootColor;\n    if (uVisualState > 1.5)\n    {\n        currentLightsColor = retryColor;\n    }\n    else\n    {\n        if (uVisualState > 0.5)\n        {\n            currentLightsColor = warningColor;\n        }\n    }\n    vec3 lights_col_f = currentLightsColor * f;\n    float bgGlow = 0.0500000007450580596923828125 / (length(p) + 0.5);\n    vec3 bg_col = currentLightsColor * bgGlow;\n    vec3 final_rgb = bg_col + lights_col_f;\n    float final_alpha = (bgGlow * 2.0) + (f * 0.20000000298023223876953125);\n    fragColor = vec4(final_rgb, final_alpha);\n}\n\nhalf4 main(float2 iFragCoord)\n{\n      flutter_FragCoord = float4(iFragCoord, 0, 0);\n      FLT_main();\n      return fragColor;\n}\n",
    "stage": 1,
    "uniforms": [
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 0,
        "name": "iResolution",
        "rows": 2,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 1,
        "name": "iTime",
        "rows": 1,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 2,
        "name": "uVisualState",
        "rows": 1,
        "type": 10
      }
    ]
  }
}