package com.kerosene.auth.application.usecase.devicekey;

import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;
import com.kerosene.auth.application.orchestrator.signup.port.SignupStateStore;
import com.kerosene.auth.application.service.devicekey.DeviceKeyService;
import com.kerosene.auth.dto.SignupState;
import com.kerosene.auth.dto.devicekey.DeviceKeyChallengeResponse;

import java.time.Duration;

/** Starts device-key registration using the pending signup session as its identity context. */
@Component
public class StartOnboardingDeviceKeyRegistrationUseCase {

    /** Signup-state lifetime refreshed when the onboarding username is first attached. */
    private static final Duration SIGNUP_STATE_TTL = Duration.ofMinutes(1440);

    /** Port for reading and refreshing pending signup state. */
    private final SignupStateStore signupStateStore;
    /** Device-key protocol service that creates the registration challenge. */
    private final DeviceKeyService deviceKeyService;

    /**
     * Creates the onboarding registration starter.
     *
     * @param signupStateStore temporary signup-state boundary
     * @param deviceKeyService device-key challenge and verification service
     */
    public StartOnboardingDeviceKeyRegistrationUseCase(
            SignupStateStore signupStateStore,
            DeviceKeyService deviceKeyService) {
        this.signupStateStore = signupStateStore;
        this.deviceKeyService = deviceKeyService;
    }

    /**
     * Loads signup state, optionally normalizes and records a missing username, then creates a
     * device-key challenge bound to that signup session and username.
     *
     * @param sessionId signup session whose temporary state owns the challenge
     * @param username optional username supplied to fill an empty state username
     * @return generated challenge or an expired-session result
     */
    @Transactional
    public Result execute(String sessionId, String username) {
        SignupState state = signupStateStore.findSignupState(sessionId);
        if (state == null) {
            return Result.sessionExpired();
        }

        if ((state.getUsername() == null || state.getUsername().isBlank())
                && username != null && !username.isBlank()) {
            state.setUsername(DeviceKeyUsernameSupport.normalizeUsername(username));
            signupStateStore.saveSignupState(sessionId, state, SIGNUP_STATE_TTL);
        }

        DeviceKeyChallengeResponse challenge = deviceKeyService.startRegistrationChallenge(
                sessionId,
                state.getUsername());
        return Result.generated(challenge);
    }

    /**
     * Result of starting device-key registration during account onboarding.
     * @param status whether a challenge was created or the signup session expired
     * @param challenge challenge payload, present only for {@link Status#GENERATED}
     */
    public record Result(Status status, DeviceKeyChallengeResponse challenge) {

        /** Builds the successful challenge result. */
        /** @param challenge challenge generated by the device-key service */
        /** @return generated result */
        public static Result generated(DeviceKeyChallengeResponse challenge) {
            return new Result(Status.GENERATED, challenge);
        }

        /** Builds the result returned when the signup state no longer exists. */
        /** @return expired-session result with no challenge */
        public static Result sessionExpired() {
            return new Result(Status.SESSION_EXPIRED, null);
        }
    }

    /** Possible outcomes when starting onboarding device-key registration. */
    public enum Status {
        /** A registration challenge was generated. */
        GENERATED,
        /** Signup state was absent or expired. */
        SESSION_EXPIRED
    }
}
