package com.kerosene.auth.dto;

import java.util.List;

/**
 * Backup-code enrollment summary; newly generated plaintext codes are returned only once.
 * @param enabled whether backup-code recovery is available
 * @param remainingCodes number of unused codes still stored
 * @param newlyGeneratedCodes plaintext codes generated by the current operation, otherwise empty
 */
public record BackupCodesStatusDTO(
        boolean enabled,
        int remainingCodes,
        List<String> newlyGeneratedCodes) {
}
