package com.kerosene.auth.application.service.account;

import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import com.kerosene.auth.application.service.crypto.contracts.Hasher;
import com.kerosene.auth.application.service.user.contract.UserServiceContract;
import com.kerosene.auth.dto.BackupCodesStatusDTO;
import com.kerosene.auth.model.entity.UserDataBase;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

/** Reports and rotates one-time backup codes, storing only password-hash representations. */
@Service
public class BackupCodeService {

    /** Number of codes generated by each rotation. */
    private static final int BACKUP_CODE_COUNT = 10;
    /** Exclusive random bound for eight-digit zero-padded values. */
    private static final int BACKUP_CODE_BOUND = 100_000_000;

    /** Account lookup and persistence boundary. */
    private final UserServiceContract userService;
    /** Argon2-qualified hasher for one-time code storage. */
    private final Hasher hasher;
    /** Cryptographically secure source for recovery code values. */
    private final SecureRandom random = new SecureRandom();

    /** Creates the backup-code service. */
    /** @param userService account lookup and persistence */
    /** @param hasher Argon2 code hasher */
    public BackupCodeService(
            UserServiceContract userService,
            @Qualifier("Argon2Hasher") Hasher hasher) {
        this.userService = userService;
        this.hasher = hasher;
    }

    /** Returns whether codes remain and how many, never returning stored hashes. */
    /** @param userId account identifier */
    /** @return status projection with an empty raw-code list */
    public BackupCodesStatusDTO getStatus(Long userId) {
        UserDataBase user = requireUser(userId);
        int remaining = user.getBackupCodes() != null ? user.getBackupCodes().size() : 0;
        return new BackupCodesStatusDTO(remaining > 0, remaining, List.of());
    }

    /** Rotates the user's code set, persists only hashes, and returns new raw codes once. */
    /** @param userId account identifier */
    /** @return status and newly generated codes for one-time display */
    @Transactional
    public BackupCodesStatusDTO regenerate(Long userId) {
        UserDataBase user = requireUser(userId);
        GeneratedBackupCodes generated = generateBackupCodes();
        user.setBackupCodes(generated.hashedCodes());
        userService.createUserInDataBase(user);
        return new BackupCodesStatusDTO(true, generated.hashedCodes().size(), generated.rawCodes());
    }

    /** Loads the account or reports that its authenticated identity is stale. */
    /** @param userId account identifier */
    /** @return persisted account */
    /** @throws IllegalStateException when account lookup fails */
    private UserDataBase requireUser(Long userId) {
        return userService.buscarPorId(userId)
                .orElseThrow(() -> new IllegalStateException("Authenticated user not found."));
    }

    /** Generates random eight-digit codes, retains raw values for display, hashes the stored set, and zeroes character buffers. */
    /** @return paired raw and encoded code lists */
    private GeneratedBackupCodes generateBackupCodes() {
        List<String> rawCodes = new ArrayList<>();
        List<String> hashedCodes = new ArrayList<>();

        for (int i = 0; i < BACKUP_CODE_COUNT; i++) {
            String code = String.format("%08d", random.nextInt(BACKUP_CODE_BOUND));
            rawCodes.add(code);
            char[] codeChars = code.toCharArray();
            try {
                hashedCodes.add(hasher.hash(codeChars));
            } finally {
                Arrays.fill(codeChars, '\0');
            }
        }

        return new GeneratedBackupCodes(rawCodes, hashedCodes);
    }

    /**
     * Holds raw codes for the response and their encoded counterparts for persistence.
     * @param rawCodes codes disclosed once to the user
     * @param hashedCodes encoded values saved on the account
     */
    private record GeneratedBackupCodes(List<String> rawCodes, List<String> hashedCodes) {
    }
}
