name: Core CI

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  java:
    uses: Daniel-Astrofer/.github/.github/workflows/java-ci.yml@7b1da98fbf1159e80b7ea3d055a137d749226d2f
    with:
      gradle-arguments: test

  security:
    uses: Daniel-Astrofer/.github/.github/workflows/security-scan.yml@7b1da98fbf1159e80b7ea3d055a137d749226d2f
